CREATE TABLE MARATHON(
    Place INT AUTO_INCREMENT PRIMARY KEY,
    Time TIME  NOT NULL,
    Pace VARCHAR(10) NOT NULL,
    GroupPlace INT NOT NULL,
    `Group` VARCHAR(10) NOT NULL,
    Age INT NOT NULL,
    Sex CHAR(1) NOT NULL,
    BIBNumber INT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Town VARCHAR(50) NOT NULL,
    State VARCHAR(10) NOT NULL
);

DROP TABLE MARATHON;