CREATE TABLE TEACHERS(
LastName VARCHAR(50) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
Classroom TINYINT UNSIGNED NOT NULL PRIMARY KEY
);

CREATE TABLE LIST(
LastName VARCHAR(50) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
Grade TINYINT UNSIGNED NOT NULL,
Classroom TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (LastName, FirstName),
CONSTRAINT fk_room
    FOREIGN KEY (Classroom) REFERENCES TEACHERS(Classroom)
    ON DELETE CASCADE
);