CREATE TABLE ALBUMS(
    AId INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    Year CHAR(4) NOT NULL,
    Label VARCHAR(30) NOT NULL
);
CREATE TABLE BAND(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Firstname VARCHAR(50) NOT NULL,
    Lastname VARCHAR(50) NOT NULL
);
CREATE TABLE SONGS(
    SongId INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(50) NOT NULL
);
CREATE TABLE INSTRUMENTS(
    SongId INT NOT NULL,
    BandmateId INT NOT NULL,
    Instrument VARCHAR(30) NOT NULL,
    PRIMARY KEY (SongId, BandmateId, Instrument),
    FOREIGN KEY (SongId) REFERENCES SONGS (SongId),
    FOREIGN KEY (BandmateId) REFERENCES BAND (Id)
);
CREATE TABLE PERFORMANCE(
    SongId INT NOT NULL,
    Bandmate INT NOT NULL,
    StagePosition VARCHAR(50) NOT NULL,
    PRIMARY KEY (SongId, Bandmate),
    FOREIGN KEY (SongId) REFERENCES SONGS (SongId),
    FOREIGN KEY (Bandmate) REFERENCES BAND (Id)
);
CREATE TABLE TRACKLISTS(
    AlbumId INT NOT NULL,
    Position INT NOT NULL,
    SongId INT NOT NULL,
    PRIMARY KEY (AlbumId, SongId),
    FOREIGN KEY (AlbumId) REFERENCES ALBUMS (AId),
    FOREIGN KEY (SongId) REFERENCES SONGS (SongId)
);
CREATE TABLE VOCALS(
    SongId INT NOT NULL,
    Bandmate INT NOT NULL,
    Type VARCHAR(15) NOT NULL,
    PRIMARY KEY (SongId, Bandmate, Type),
    FOREIGN KEY (SongId) REFERENCES SONGS (SongId),
    FOREIGN KEY (Bandmate) REFERENCES BAND (Id)
);

-- DROP TABLE VOCALS;
-- DROP TABLE TRACKLISTS;
-- DROP TABLE PERFORMANCE;
-- DROP TABLE INSTRUMENTS;
-- DROP TABLE SONGS;
-- DROP TABLE BAND;
-- DROP TABLE ALBUMS;