CREATE TABLE APPELLATION(
No TINYINT UNSIGNED auto_increment PRIMARY KEY,
Appellation VARCHAR(50) NOT NULL UNIQUE,
County VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
Area VARCHAR(50) NOT NULL,
isAVA VARCHAR(3) NOT NULL 
);

CREATE TABLE GRAPES(
ID TINYINT UNSIGNED auto_increment PRIMARY KEY,
Grape VARCHAR(50) NOT NULL UNIQUE,
Color VARCHAR(10) NOT NULL
);

CREATE TABLE WINE(
No SMALLINT UNSIGNED auto_increment PRIMARY KEY,
Grape VARCHAR(50),
Winery VARCHAR(50) NOT NULL,
Appellation VARCHAR(50),
Name VARCHAR(50) NOT NULL,
Year CHAR(4) NOT NULL,
Price TINYINT UNSIGNED NOT NULL,
Score TINYINT UNSIGNED NOT NULL,
Cases INT UNSIGNED,
CONSTRAINT fk_Grape
    FOREIGN KEY (Grape) REFERENCES GRAPES(Grape)
    ON DELETE CASCADE,
CONSTRAINT fk_Appellation
    FOREIGN KEY (Appellation) REFERENCES APPELLATION(Appellation)
    ON DELETE CASCADE
);